Default: &defaults
  database: scheduler.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: scheduler_test.sqlite3
  <<: *defaults

Staging:
  database: scheduler_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: scheduler_production.sqlite3
  poolsize: 100
  <<: *defaults
